name: Publish backfill image
on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "index.mjs"
      - "package.json"
      - "action.yml"
      - ".dockerignore"
      - ".github/workflows/publish-backfill-image.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set chrono-backfill image name
        shell: bash
        run: echo "IMAGE_NAME=ghcr.io/${OWNER,,}/chrono-backfill" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=dev
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
